/**
 * Copyright 2013 Joan Zapata
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * It uses FontAwesome font, licensed under OFL 1.1, which is compatible
 * with this library's license.
 *
 *     http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=OFL_plaintext&filename=OFL.txt
 */
package com.joanzapata.android.iconify;

import android.content.Context;
import android.graphics.Typeface;
import android.text.Spanned;
import android.widget.TextView;

import java.io.IOException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import static android.text.Html.fromHtml;
import static android.text.Html.toHtml;
import static com.joanzapata.android.iconify.Utils.replaceIcons;
import static com.joanzapata.android.iconify.Utils.resourceToFile;
import static java.lang.String.valueOf;

public final class Iconify {


	public static final String TAG = Iconify.class.getSimpleName();

	private static final Map<String, String> TTF_FILES = new HashMap<String, String>();
	private static final Map<String, Typeface> TYPEFACES = new HashMap<String, Typeface>();

	static {
		TTF_FILES.put("fa", "fontawesome-webfont-4.2.0.ttf");
		TTF_FILES.put("gy", "glyphicons-halflings-regular.ttf");
		TTF_FILES.put("gmd", "google_material_design.ttf");

	}

	private Iconify() {
		// Prevent instantiation
	}

	/**
	 * Transform the given TextViews replacing {icon_xxx} texts with icons.
	 */
	public static final void addIcons(TextView... textViews) {
		for (TextView textView : textViews) {
			textView.setTypeface(getTypeface(textView));
			textView.setText(compute(textView.getText()));
		}
	}

	public static CharSequence compute(CharSequence charSequence) {
		if (charSequence instanceof Spanned) {
			String text = toHtml((Spanned) charSequence);
			return fromHtml(replaceIcons(new StringBuilder((text)), TTF_FILES.keySet().iterator()).toString());
		}
		String text = charSequence.toString();
		return replaceIcons(new StringBuilder(text), TTF_FILES.keySet().iterator());
	}

	public static final void setIcon(TextView textView, IconValue value) {
		textView.setTypeface(getTypeface(textView));
		textView.setText(valueOf(value.character));
	}

	/**
	 * The typeface that contains FontAwesome icons.
	 *
	 * @return the typeface, or null if something goes wrong.
	 */
	public static final Typeface getTypeface(Context context) {
		return getTypeface(context, "fa");
	}

	public static final Typeface getTypeface(TextView textView) {
		Iterator<String> iterator = TTF_FILES.keySet().iterator();
		String text = textView.getText().toString();
		String type;
		while (iterator.hasNext()) {
			type = iterator.next();
			if (text.indexOf("{" + type) != -1) {
				return getTypeface(textView.getContext(), type);
			}
		}
		return null;
	}

	private static final Typeface getTypeface(Context context, String type) {
		Typeface typeface = TYPEFACES.get(type);
		if (typeface == null) {
			try {
				typeface = Typeface.createFromFile(resourceToFile(context, TTF_FILES.get(type)));
				TYPEFACES.put(type, typeface);
			} catch (IOException e) {
				return null;
			}
		}
		return typeface;
	}


	public static enum IconValue {

		fa_adjust('\uf042'),
		fa_adn('\uf170'),
		fa_align_center('\uf037'),
		fa_align_justify('\uf039'),
		fa_align_left('\uf036'),
		fa_align_right('\uf038'),
		fa_ambulance('\uf0f9'),
		fa_anchor('\uf13d'),
		fa_android('\uf17b'),
		fa_angellist('\uf209'),
		fa_angle_double_down('\uf103'),
		fa_angle_double_left('\uf100'),
		fa_angle_double_right('\uf101'),
		fa_angle_double_up('\uf102'),
		fa_angle_down('\uf107'),
		fa_angle_left('\uf104'),
		fa_angle_right('\uf105'),
		fa_angle_up('\uf106'),
		fa_apple('\uf179'),
		fa_archive('\uf187'),
		fa_area_chart('\uf1fe'),
		fa_arrow_circle_down('\uf0ab'),
		fa_arrow_circle_left('\uf0a8'),
		fa_arrow_circle_o_down('\uf01a'),
		fa_arrow_circle_o_left('\uf190'),
		fa_arrow_circle_o_right('\uf18e'),
		fa_arrow_circle_o_up('\uf01b'),
		fa_arrow_circle_right('\uf0a9'),
		fa_arrow_circle_up('\uf0aa'),
		fa_arrow_down('\uf063'),
		fa_arrow_left('\uf060'),
		fa_arrow_right('\uf061'),
		fa_arrow_up('\uf062'),
		fa_arrows('\uf047'),
		fa_arrows_alt('\uf0b2'),
		fa_arrows_h('\uf07e'),
		fa_arrows_v('\uf07d'),
		fa_asterisk('\uf069'),
		fa_at('\uf1fa'),
		fa_automobile('\uf1b9'),
		fa_backward('\uf04a'),
		fa_ban('\uf05e'),
		fa_bank('\uf19c'),
		fa_bar_chart('\uf080'),
		fa_bar_chart_o('\uf080'),
		fa_barcode('\uf02a'),
		fa_bars('\uf0c9'),
		fa_beer('\uf0fc'),
		fa_behance('\uf1b4'),
		fa_behance_square('\uf1b5'),
		fa_bell('\uf0f3'),
		fa_bell_o('\uf0a2'),
		fa_bell_slash('\uf1f6'),
		fa_bell_slash_o('\uf1f7'),
		fa_bicycle('\uf206'),
		fa_binoculars('\uf1e5'),
		fa_birthday_cake('\uf1fd'),
		fa_bitbucket('\uf171'),
		fa_bitbucket_square('\uf172'),
		fa_bitcoin('\uf15a'),
		fa_bold('\uf032'),
		fa_bolt('\uf0e7'),
		fa_bomb('\uf1e2'),
		fa_book('\uf02d'),
		fa_bookmark('\uf02e'),
		fa_bookmark_o('\uf097'),
		fa_briefcase('\uf0b1'),
		fa_btc('\uf15a'),
		fa_bug('\uf188'),
		fa_building('\uf1ad'),
		fa_building_o('\uf0f7'),
		fa_bullhorn('\uf0a1'),
		fa_bullseye('\uf140'),
		fa_bus('\uf207'),
		fa_cab('\uf1ba'),
		fa_calculator('\uf1ec'),
		fa_calendar('\uf073'),
		fa_calendar_o('\uf133'),
		fa_camera('\uf030'),
		fa_camera_retro('\uf083'),
		fa_car('\uf1b9'),
		fa_caret_down('\uf0d7'),
		fa_caret_left('\uf0d9'),
		fa_caret_right('\uf0da'),
		fa_caret_square_o_down('\uf150'),
		fa_caret_square_o_left('\uf191'),
		fa_caret_square_o_right('\uf152'),
		fa_caret_square_o_up('\uf151'),
		fa_caret_up('\uf0d8'),
		fa_cc('\uf20a'),
		fa_cc_amex('\uf1f3'),
		fa_cc_discover('\uf1f2'),
		fa_cc_mastercard('\uf1f1'),
		fa_cc_paypal('\uf1f4'),
		fa_cc_stripe('\uf1f5'),
		fa_cc_visa('\uf1f0'),
		fa_certificate('\uf0a3'),
		fa_chain('\uf0c1'),
		fa_chain_broken('\uf127'),
		fa_check('\uf00c'),
		fa_check_circle('\uf058'),
		fa_check_circle_o('\uf05d'),
		fa_check_square('\uf14a'),
		fa_check_square_o('\uf046'),
		fa_chevron_circle_down('\uf13a'),
		fa_chevron_circle_left('\uf137'),
		fa_chevron_circle_right('\uf138'),
		fa_chevron_circle_up('\uf139'),
		fa_chevron_down('\uf078'),
		fa_chevron_left('\uf053'),
		fa_chevron_right('\uf054'),
		fa_chevron_up('\uf077'),
		fa_child('\uf1ae'),
		fa_circle('\uf111'),
		fa_circle_o('\uf10c'),
		fa_circle_o_notch('\uf1ce'),
		fa_circle_thin('\uf1db'),
		fa_clipboard('\uf0ea'),
		fa_clock_o('\uf017'),
		fa_close('\uf00d'),
		fa_cloud('\uf0c2'),
		fa_cloud_download('\uf0ed'),
		fa_cloud_upload('\uf0ee'),
		fa_cny('\uf157'),
		fa_code('\uf121'),
		fa_code_fork('\uf126'),
		fa_codepen('\uf1cb'),
		fa_coffee('\uf0f4'),
		fa_cog('\uf013'),
		fa_cogs('\uf085'),
		fa_columns('\uf0db'),
		fa_comment('\uf075'),
		fa_comment_o('\uf0e5'),
		fa_comments('\uf086'),
		fa_comments_o('\uf0e6'),
		fa_compass('\uf14e'),
		fa_compress('\uf066'),
		fa_copy('\uf0c5'),
		fa_copyright('\uf1f9'),
		fa_credit_card('\uf09d'),
		fa_crop('\uf125'),
		fa_crosshairs('\uf05b'),
		fa_css3('\uf13c'),
		fa_cube('\uf1b2'),
		fa_cubes('\uf1b3'),
		fa_cut('\uf0c4'),
		fa_cutlery('\uf0f5'),
		fa_dashboard('\uf0e4'),
		fa_database('\uf1c0'),
		fa_dedent('\uf03b'),
		fa_delicious('\uf1a5'),
		fa_desktop('\uf108'),
		fa_deviantart('\uf1bd'),
		fa_digg('\uf1a6'),
		fa_dollar('\uf155'),
		fa_dot_circle_o('\uf192'),
		fa_download('\uf019'),
		fa_dribbble('\uf17d'),
		fa_dropbox('\uf16b'),
		fa_drupal('\uf1a9'),
		fa_edit('\uf044'),
		fa_eject('\uf052'),
		fa_ellipsis_h('\uf141'),
		fa_ellipsis_v('\uf142'),
		fa_empire('\uf1d1'),
		fa_envelope('\uf0e0'),
		fa_envelope_o('\uf003'),
		fa_envelope_square('\uf199'),
		fa_eraser('\uf12d'),
		fa_eur('\uf153'),
		fa_euro('\uf153'),
		fa_exchange('\uf0ec'),
		fa_exclamation('\uf12a'),
		fa_exclamation_circle('\uf06a'),
		fa_exclamation_triangle('\uf071'),
		fa_expand('\uf065'),
		fa_external_link('\uf08e'),
		fa_external_link_square('\uf14c'),
		fa_eye('\uf06e'),
		fa_eye_slash('\uf070'),
		fa_eyedropper('\uf1fb'),
		fa_facebook('\uf09a'),
		fa_facebook_square('\uf082'),
		fa_fast_backward('\uf049'),
		fa_fast_forward('\uf050'),
		fa_fax('\uf1ac'),
		fa_female('\uf182'),
		fa_fighter_jet('\uf0fb'),
		fa_file('\uf15b'),
		fa_file_archive_o('\uf1c6'),
		fa_file_audio_o('\uf1c7'),
		fa_file_code_o('\uf1c9'),
		fa_file_excel_o('\uf1c3'),
		fa_file_image_o('\uf1c5'),
		fa_file_movie_o('\uf1c8'),
		fa_file_o('\uf016'),
		fa_file_pdf_o('\uf1c1'),
		fa_file_photo_o('\uf1c5'),
		fa_file_picture_o('\uf1c5'),
		fa_file_powerpoint_o('\uf1c4'),
		fa_file_sound_o('\uf1c7'),
		fa_file_text('\uf15c'),
		fa_file_text_o('\uf0f6'),
		fa_file_video_o('\uf1c8'),
		fa_file_word_o('\uf1c2'),
		fa_file_zip_o('\uf1c6'),
		fa_files_o('\uf0c5'),
		fa_film('\uf008'),
		fa_filter('\uf0b0'),
		fa_fire('\uf06d'),
		fa_fire_extinguisher('\uf134'),
		fa_flag('\uf024'),
		fa_flag_checkered('\uf11e'),
		fa_flag_o('\uf11d'),
		fa_flash('\uf0e7'),
		fa_flask('\uf0c3'),
		fa_flickr('\uf16e'),
		fa_floppy_o('\uf0c7'),
		fa_folder('\uf07b'),
		fa_folder_o('\uf114'),
		fa_folder_open('\uf07c'),
		fa_folder_open_o('\uf115'),
		fa_font('\uf031'),
		fa_forward('\uf04e'),
		fa_foursquare('\uf180'),
		fa_frown_o('\uf119'),
		fa_futbol_o('\uf1e3'),
		fa_gamepad('\uf11b'),
		fa_gavel('\uf0e3'),
		fa_gbp('\uf154'),
		fa_ge('\uf1d1'),
		fa_gear('\uf013'),
		fa_gears('\uf085'),
		fa_gift('\uf06b'),
		fa_git('\uf1d3'),
		fa_git_square('\uf1d2'),
		fa_github('\uf09b'),
		fa_github_alt('\uf113'),
		fa_github_square('\uf092'),
		fa_gittip('\uf184'),
		fa_glass('\uf000'),
		fa_globe('\uf0ac'),
		fa_google('\uf1a0'),
		fa_google_plus('\uf0d5'),
		fa_google_plus_square('\uf0d4'),
		fa_google_wallet('\uf1ee'),
		fa_graduation_cap('\uf19d'),
		fa_group('\uf0c0'),
		fa_h_square('\uf0fd'),
		fa_hacker_news('\uf1d4'),
		fa_hand_o_down('\uf0a7'),
		fa_hand_o_left('\uf0a5'),
		fa_hand_o_right('\uf0a4'),
		fa_hand_o_up('\uf0a6'),
		fa_hdd_o('\uf0a0'),
		fa_header('\uf1dc'),
		fa_headphones('\uf025'),
		fa_heart('\uf004'),
		fa_heart_o('\uf08a'),
		fa_history('\uf1da'),
		fa_home('\uf015'),
		fa_hospital_o('\uf0f8'),
		fa_html5('\uf13b'),
		fa_ils('\uf20b'),
		fa_image('\uf03e'),
		fa_inbox('\uf01c'),
		fa_indent('\uf03c'),
		fa_info('\uf129'),
		fa_info_circle('\uf05a'),
		fa_inr('\uf156'),
		fa_instagram('\uf16d'),
		fa_institution('\uf19c'),
		fa_ioxhost('\uf208'),
		fa_italic('\uf033'),
		fa_joomla('\uf1aa'),
		fa_jpy('\uf157'),
		fa_jsfiddle('\uf1cc'),
		fa_key('\uf084'),
		fa_keyboard_o('\uf11c'),
		fa_krw('\uf159'),
		fa_language('\uf1ab'),
		fa_laptop('\uf109'),
		fa_lastfm('\uf202'),
		fa_lastfm_square('\uf203'),
		fa_leaf('\uf06c'),
		fa_legal('\uf0e3'),
		fa_lemon_o('\uf094'),
		fa_level_down('\uf149'),
		fa_level_up('\uf148'),
		fa_life_bouy('\uf1cd'),
		fa_life_buoy('\uf1cd'),
		fa_life_ring('\uf1cd'),
		fa_life_saver('\uf1cd'),
		fa_lightbulb_o('\uf0eb'),
		fa_line_chart('\uf201'),
		fa_link('\uf0c1'),
		fa_linkedin('\uf0e1'),
		fa_linkedin_square('\uf08c'),
		fa_linux('\uf17c'),
		fa_list('\uf03a'),
		fa_list_alt('\uf022'),
		fa_list_ol('\uf0cb'),
		fa_list_ul('\uf0ca'),
		fa_location_arrow('\uf124'),
		fa_lock('\uf023'),
		fa_long_arrow_down('\uf175'),
		fa_long_arrow_left('\uf177'),
		fa_long_arrow_right('\uf178'),
		fa_long_arrow_up('\uf176'),
		fa_magic('\uf0d0'),
		fa_magnet('\uf076'),
		fa_mail_forward('\uf064'),
		fa_mail_reply('\uf112'),
		fa_mail_reply_all('\uf122'),
		fa_male('\uf183'),
		fa_map_marker('\uf041'),
		fa_maxcdn('\uf136'),
		fa_meanpath('\uf20c'),
		fa_medkit('\uf0fa'),
		fa_meh_o('\uf11a'),
		fa_microphone('\uf130'),
		fa_microphone_slash('\uf131'),
		fa_minus('\uf068'),
		fa_minus_circle('\uf056'),
		fa_minus_square('\uf146'),
		fa_minus_square_o('\uf147'),
		fa_mobile('\uf10b'),
		fa_mobile_phone('\uf10b'),
		fa_money('\uf0d6'),
		fa_moon_o('\uf186'),
		fa_mortar_board('\uf19d'),
		fa_music('\uf001'),
		fa_navicon('\uf0c9'),
		fa_newspaper_o('\uf1ea'),
		fa_openid('\uf19b'),
		fa_outdent('\uf03b'),
		fa_pagelines('\uf18c'),
		fa_paint_brush('\uf1fc'),
		fa_paper_plane('\uf1d8'),
		fa_paper_plane_o('\uf1d9'),
		fa_paperclip('\uf0c6'),
		fa_paragraph('\uf1dd'),
		fa_paste('\uf0ea'),
		fa_pause('\uf04c'),
		fa_paw('\uf1b0'),
		fa_paypal('\uf1ed'),
		fa_pencil('\uf040'),
		fa_pencil_square('\uf14b'),
		fa_pencil_square_o('\uf044'),
		fa_phone('\uf095'),
		fa_phone_square('\uf098'),
		fa_photo('\uf03e'),
		fa_picture_o('\uf03e'),
		fa_pie_chart('\uf200'),
		fa_pied_piper('\uf1a7'),
		fa_pied_piper_alt('\uf1a8'),
		fa_pinterest('\uf0d2'),
		fa_pinterest_square('\uf0d3'),
		fa_plane('\uf072'),
		fa_play('\uf04b'),
		fa_play_circle('\uf144'),
		fa_play_circle_o('\uf01d'),
		fa_plug('\uf1e6'),
		fa_plus('\uf067'),
		fa_plus_circle('\uf055'),
		fa_plus_square('\uf0fe'),
		fa_plus_square_o('\uf196'),
		fa_power_off('\uf011'),
		fa_print('\uf02f'),
		fa_puzzle_piece('\uf12e'),
		fa_qq('\uf1d6'),
		fa_qrcode('\uf029'),
		fa_question('\uf128'),
		fa_question_circle('\uf059'),
		fa_quote_left('\uf10d'),
		fa_quote_right('\uf10e'),
		fa_ra('\uf1d0'),
		fa_random('\uf074'),
		fa_rebel('\uf1d0'),
		fa_recycle('\uf1b8'),
		fa_reddit('\uf1a1'),
		fa_reddit_square('\uf1a2'),
		fa_refresh('\uf021'),
		fa_remove('\uf00d'),
		fa_renren('\uf18b'),
		fa_reorder('\uf0c9'),
		fa_repeat('\uf01e'),
		fa_reply('\uf112'),
		fa_reply_all('\uf122'),
		fa_retweet('\uf079'),
		fa_rmb('\uf157'),
		fa_road('\uf018'),
		fa_rocket('\uf135'),
		fa_rotate_left('\uf0e2'),
		fa_rotate_right('\uf01e'),
		fa_rouble('\uf158'),
		fa_rss('\uf09e'),
		fa_rss_square('\uf143'),
		fa_rub('\uf158'),
		fa_ruble('\uf158'),
		fa_rupee('\uf156'),
		fa_save('\uf0c7'),
		fa_scissors('\uf0c4'),
		fa_search('\uf002'),
		fa_search_minus('\uf010'),
		fa_search_plus('\uf00e'),
		fa_send('\uf1d8'),
		fa_send_o('\uf1d9'),
		fa_share('\uf064'),
		fa_share_alt('\uf1e0'),
		fa_share_alt_square('\uf1e1'),
		fa_share_square('\uf14d'),
		fa_share_square_o('\uf045'),
		fa_shekel('\uf20b'),
		fa_sheqel('\uf20b'),
		fa_shield('\uf132'),
		fa_shopping_cart('\uf07a'),
		fa_sign_in('\uf090'),
		fa_sign_out('\uf08b'),
		fa_signal('\uf012'),
		fa_sitemap('\uf0e8'),
		fa_skype('\uf17e'),
		fa_slack('\uf198'),
		fa_sliders('\uf1de'),
		fa_slideshare('\uf1e7'),
		fa_smile_o('\uf118'),
		fa_soccer_ball_o('\uf1e3'),
		fa_sort('\uf0dc'),
		fa_sort_alpha_asc('\uf15d'),
		fa_sort_alpha_desc('\uf15e'),
		fa_sort_amount_asc('\uf160'),
		fa_sort_amount_desc('\uf161'),
		fa_sort_asc('\uf0de'),
		fa_sort_desc('\uf0dd'),
		fa_sort_down('\uf0dd'),
		fa_sort_numeric_asc('\uf162'),
		fa_sort_numeric_desc('\uf163'),
		fa_sort_up('\uf0de'),
		fa_soundcloud('\uf1be'),
		fa_space_shuttle('\uf197'),
		fa_spinner('\uf110'),
		fa_spoon('\uf1b1'),
		fa_spotify('\uf1bc'),
		fa_square('\uf0c8'),
		fa_square_o('\uf096'),
		fa_stack_exchange('\uf18d'),
		fa_stack_overflow('\uf16c'),
		fa_star('\uf005'),
		fa_star_half('\uf089'),
		fa_star_half_empty('\uf123'),
		fa_star_half_full('\uf123'),
		fa_star_half_o('\uf123'),
		fa_star_o('\uf006'),
		fa_steam('\uf1b6'),
		fa_steam_square('\uf1b7'),
		fa_step_backward('\uf048'),
		fa_step_forward('\uf051'),
		fa_stethoscope('\uf0f1'),
		fa_stop('\uf04d'),
		fa_strikethrough('\uf0cc'),
		fa_stumbleupon('\uf1a4'),
		fa_stumbleupon_circle('\uf1a3'),
		fa_subscript('\uf12c'),
		fa_suitcase('\uf0f2'),
		fa_sun_o('\uf185'),
		fa_superscript('\uf12b'),
		fa_support('\uf1cd'),
		fa_table('\uf0ce'),
		fa_tablet('\uf10a'),
		fa_tachometer('\uf0e4'),
		fa_tag('\uf02b'),
		fa_tags('\uf02c'),
		fa_tasks('\uf0ae'),
		fa_taxi('\uf1ba'),
		fa_tencent_weibo('\uf1d5'),
		fa_terminal('\uf120'),
		fa_text_height('\uf034'),
		fa_text_width('\uf035'),
		fa_th('\uf00a'),
		fa_th_large('\uf009'),
		fa_th_list('\uf00b'),
		fa_thumb_tack('\uf08d'),
		fa_thumbs_down('\uf165'),
		fa_thumbs_o_down('\uf088'),
		fa_thumbs_o_up('\uf087'),
		fa_thumbs_up('\uf164'),
		fa_ticket('\uf145'),
		fa_times('\uf00d'),
		fa_times_circle('\uf057'),
		fa_times_circle_o('\uf05c'),
		fa_tint('\uf043'),
		fa_toggle_down('\uf150'),
		fa_toggle_left('\uf191'),
		fa_toggle_off('\uf204'),
		fa_toggle_on('\uf205'),
		fa_toggle_right('\uf152'),
		fa_toggle_up('\uf151'),
		fa_trash('\uf1f8'),
		fa_trash_o('\uf014'),
		fa_tree('\uf1bb'),
		fa_trello('\uf181'),
		fa_trophy('\uf091'),
		fa_truck('\uf0d1'),
		fa_try('\uf195'),
		fa_tty('\uf1e4'),
		fa_tumblr('\uf173'),
		fa_tumblr_square('\uf174'),
		fa_turkish_lira('\uf195'),
		fa_twitch('\uf1e8'),
		fa_twitter('\uf099'),
		fa_twitter_square('\uf081'),
		fa_umbrella('\uf0e9'),
		fa_underline('\uf0cd'),
		fa_undo('\uf0e2'),
		fa_university('\uf19c'),
		fa_unlink('\uf127'),
		fa_unlock('\uf09c'),
		fa_unlock_alt('\uf13e'),
		fa_unsorted('\uf0dc'),
		fa_upload('\uf093'),
		fa_usd('\uf155'),
		fa_user('\uf007'),
		fa_user_md('\uf0f0'),
		fa_users('\uf0c0'),
		fa_video_camera('\uf03d'),
		fa_vimeo_square('\uf194'),
		fa_vine('\uf1ca'),
		fa_vk('\uf189'),
		fa_volume_down('\uf027'),
		fa_volume_off('\uf026'),
		fa_volume_up('\uf028'),
		fa_warning('\uf071'),
		fa_wechat('\uf1d7'),
		fa_weibo('\uf18a'),
		fa_weixin('\uf1d7'),
		fa_wheelchair('\uf193'),
		fa_wifi('\uf1eb'),
		fa_windows('\uf17a'),
		fa_won('\uf159'),
		fa_wordpress('\uf19a'),
		fa_wrench('\uf0ad'),
		fa_xing('\uf168'),
		fa_xing_square('\uf169'),
		fa_yahoo('\uf19e'),
		fa_yelp('\uf1e9'),
		fa_yen('\uf157'),
		fa_youtube('\uf167'),
		fa_youtube_play('\uf16a'),
		fa_youtube_square('\uf166'),

		//gy_asterisk               ('\u200a'),
		//gy_plus                   ('\u200b'),
		gy_euro                   ('\u20ac'),
		gy_eur                    ('\u20ac'),
		gy_minus                  ('\u2212'),
		gy_cloud                  ('\u2601'),
		gy_envelope               ('\u2709'),
		gy_pencil                 ('\u270f'),
		gy_glass                  ('\ue001'),
		gy_music                  ('\ue002'),
		gy_search                 ('\ue003'),
		gy_heart                  ('\ue005'),
		gy_star                   ('\ue006'),
		gy_star_empty             ('\ue007'),
		gy_user                   ('\ue008'),
		gy_film                   ('\ue009'),
		gy_th_large               ('\ue010'),
		gy_th                     ('\ue011'),
		gy_th_list                ('\ue012'),
		gy_ok                     ('\ue013'),
		gy_remove                 ('\ue014'),
		gy_zoom_in                ('\ue015'),
		gy_zoom_out               ('\ue016'),
		gy_off                    ('\ue017'),
		gy_signal                 ('\ue018'),
		gy_cog                    ('\ue019'),
		gy_trash                  ('\ue020'),
		gy_home                   ('\ue021'),
		gy_file                   ('\ue022'),
		gy_time                   ('\ue023'),
		gy_road                   ('\ue024'),
		gy_download_alt           ('\ue025'),
		gy_download               ('\ue026'),
		gy_upload                 ('\ue027'),
		gy_inbox                  ('\ue028'),
		gy_play_circle            ('\ue029'),
		gy_repeat                 ('\ue030'),
		gy_refresh                ('\ue031'),
		gy_list_alt               ('\ue032'),
		gy_lock                   ('\ue033'),
		gy_flag                   ('\ue034'),
		gy_headphones             ('\ue035'),
		gy_volume_off             ('\ue036'),
		gy_volume_down            ('\ue037'),
		gy_volume_up              ('\ue038'),
		gy_qrcode                 ('\ue039'),
		gy_barcode                ('\ue040'),
		gy_tag                    ('\ue041'),
		gy_tags                   ('\ue042'),
		gy_book                   ('\ue043'),
		gy_bookmark               ('\ue044'),
		gy_print                  ('\ue045'),
		gy_camera                 ('\ue046'),
		gy_font                   ('\ue047'),
		gy_bold                   ('\ue048'),
		gy_italic                 ('\ue049'),
		gy_text_height            ('\ue050'),
		gy_text_width             ('\ue051'),
		gy_align_left             ('\ue052'),
		gy_align_center           ('\ue053'),
		gy_align_right            ('\ue054'),
		gy_align_justify          ('\ue055'),
		gy_list                   ('\ue056'),
		gy_indent_left            ('\ue057'),
		gy_indent_right           ('\ue058'),
		gy_facetime_video         ('\ue059'),
		gy_picture                ('\ue060'),
		gy_map_marker             ('\ue062'),
		gy_adjust                 ('\ue063'),
		gy_tint                   ('\ue064'),
		gy_edit                   ('\ue065'),
		gy_share                  ('\ue066'),
		gy_check                  ('\ue067'),
		gy_move                   ('\ue068'),
		gy_step_backward          ('\ue069'),
		gy_fast_backward          ('\ue070'),
		gy_backward               ('\ue071'),
		gy_play                   ('\ue072'),
		gy_pause                  ('\ue073'),
		gy_stop                   ('\ue074'),
		gy_forward                ('\ue075'),
		gy_fast_forward           ('\ue076'),
		gy_step_forward           ('\ue077'),
		gy_eject                  ('\ue078'),
		gy_chevron_left           ('\ue079'),
		gy_chevron_right          ('\ue080'),
		gy_plus_sign              ('\ue081'),
		gy_minus_sign             ('\ue082'),
		gy_remove_sign            ('\ue083'),
		gy_ok_sign                ('\ue084'),
		gy_question_sign          ('\ue085'),
		gy_info_sign              ('\ue086'),
		gy_screenshot             ('\ue087'),
		gy_remove_circle          ('\ue088'),
		gy_ok_circle              ('\ue089'),
		gy_ban_circle             ('\ue090'),
		gy_arrow_left             ('\ue091'),
		gy_arrow_right            ('\ue092'),
		gy_arrow_up               ('\ue093'),
		gy_arrow_down             ('\ue094'),
		gy_share_alt              ('\ue095'),
		gy_resize_full            ('\ue096'),
		gy_resize_small           ('\ue097'),
		gy_exclamation_sign       ('\ue101'),
		gy_gift                   ('\ue102'),
		gy_leaf                   ('\ue103'),
		gy_fire                   ('\ue104'),
		gy_eye_open               ('\ue105'),
		gy_eye_close              ('\ue106'),
		gy_warning_sign           ('\ue107'),
		gy_plane                  ('\ue108'),
		gy_calendar               ('\ue109'),
		gy_random                 ('\ue110'),
		gy_comment                ('\ue111'),
		gy_magnet                 ('\ue112'),
		gy_chevron_up             ('\ue113'),
		gy_chevron_down           ('\ue114'),
		gy_retweet                ('\ue115'),
		gy_shopping_cart          ('\ue116'),
		gy_folder_close           ('\ue117'),
		gy_folder_open            ('\ue118'),
		gy_resize_vertical        ('\ue119'),
		gy_resize_horizontal      ('\ue120'),
		gy_hdd                    ('\ue121'),
		gy_bullhorn               ('\ue122'),
		gy_bell                   ('\ue123'),
		gy_certificate            ('\ue124'),
		gy_thumbs_up              ('\ue125'),
		gy_thumbs_down            ('\ue126'),
		gy_hand_right             ('\ue127'),
		gy_hand_left              ('\ue128'),
		gy_hand_up                ('\ue129'),
		gy_hand_down              ('\ue130'),
		gy_circle_arrow_right     ('\ue131'),
		gy_circle_arrow_left      ('\ue132'),
		gy_circle_arrow_up        ('\ue133'),
		gy_circle_arrow_down      ('\ue134'),
		gy_globe                  ('\ue135'),
		gy_wrench                 ('\ue136'),
		gy_tasks                  ('\ue137'),
		gy_filter                 ('\ue138'),
		gy_briefcase              ('\ue139'),
		gy_fullscreen             ('\ue140'),
		gy_dashboard              ('\ue141'),
		gy_paperclip              ('\ue142'),
		gy_heart_empty            ('\ue143'),
		gy_link                   ('\ue144'),
		gy_phone                  ('\ue145'),
		gy_pushpin                ('\ue146'),
		gy_usd                    ('\ue148'),
		gy_gbp                    ('\ue149'),
		gy_sort                   ('\ue150'),
		gy_sort_by_alphabet       ('\ue151'),
		gy_sort_by_alphabet_alt   ('\ue152'),
		gy_sort_by_order          ('\ue153'),
		gy_sort_by_order_alt      ('\ue154'),
		gy_sort_by_attributes     ('\ue155'),
		gy_sort_by_attributes_alt ('\ue156'),
		gy_unchecked              ('\ue157'),
		gy_expand                 ('\ue158'),
		gy_collapse_down          ('\ue159'),
		gy_collapse_up            ('\ue160'),
		gy_log_in                 ('\ue161'),
		gy_flash                  ('\ue162'),
		gy_log_out                ('\ue163'),
		gy_new_window             ('\ue164'),
		gy_record                 ('\ue165'),
		gy_save                   ('\ue166'),
		gy_open                   ('\ue167'),
		gy_saved                  ('\ue168'),
		gy_import                 ('\ue169'),
		gy_export                 ('\ue170'),
		gy_send                   ('\ue171'),
		gy_floppy_disk            ('\ue172'),
		gy_floppy_saved           ('\ue173'),
		gy_floppy_remove          ('\ue174'),
		gy_floppy_save            ('\ue175'),
		gy_floppy_open            ('\ue176'),
		gy_credit_card            ('\ue177'),
		gy_transfer               ('\ue178'),
		gy_cutlery                ('\ue179'),
		gy_header                 ('\ue180'),
		gy_compressed             ('\ue181'),
		gy_earphone               ('\ue182'),
		gy_phone_alt              ('\ue183'),
		gy_tower                  ('\ue184'),
		gy_stats                  ('\ue185'),
		gy_sd_video               ('\ue186'),
		gy_hd_video               ('\ue187'),
		gy_subtitles              ('\ue188'),
		gy_sound_stereo           ('\ue189'),
		gy_sound_dolby            ('\ue190'),
		gy_sound_5_1              ('\ue191'),
		gy_sound_6_1              ('\ue192'),
		gy_sound_7_1              ('\ue193'),
		gy_copyright_mark         ('\ue194'),
		gy_registration_mark      ('\ue195'),
		gy_cloud_download         ('\ue197'),
		gy_cloud_upload           ('\ue198'),
		gy_tree_conifer           ('\ue199'),
		gy_tree_deciduous         ('\ue200'),

		gmd_3d_rotation('\ue600'),
		gmd_accessibility('\ue601'),
		gmd_account_balance('\ue602'),
		gmd_account_balance_wallet('\ue603'),
		gmd_account_box('\ue604'),
		gmd_account_child('\ue605'),
		gmd_account_circle('\ue606'),
		gmd_add_shopping_cart('\ue607'),
		gmd_alarm('\ue608'),
		gmd_alarm_add('\ue609'),
		gmd_alarm_off('\ue60a'),
		gmd_alarm_on('\ue60b'),
		gmd_android('\ue60c'),
		gmd_announcement('\ue60d'),
		gmd_aspect_ratio('\ue60e'),
		gmd_assessment('\ue60f'),
		gmd_assignment('\ue610'),
		gmd_assignment_ind('\ue611'),
		gmd_assignment_late('\ue612'),
		gmd_assignment_return('\ue613'),
		gmd_assignment_returned('\ue614'),
		gmd_assignment_turned_in('\ue615'),
		gmd_autorenew('\ue616'),
		gmd_backup('\ue617'),
		gmd_book('\ue618'),
		gmd_bookmark('\ue619'),
		gmd_bookmark_outline('\ue61a'),
		gmd_bug_report('\ue61b'),
		gmd_cached('\ue61c'),
		gmd_class('\ue61d'),
		gmd_credit_card('\ue61e'),
		gmd_dashboard('\ue61f'),
		gmd_delete('\ue620'),
		gmd_description('\ue621'),
		gmd_dns('\ue622'),
		gmd_done('\ue623'),
		gmd_done_all('\ue624'),
		gmd_event('\ue625'),
		gmd_exit_to_app('\ue626'),
		gmd_explore('\ue627'),
		gmd_extension('\ue628'),
		gmd_face_unlock('\ue629'),
		gmd_favorite('\ue62a'),
		gmd_favorite_outline('\ue62b'),
		gmd_find_in_page('\ue62c'),
		gmd_find_replace('\ue62d'),
		gmd_flip_to_back('\ue62e'),
		gmd_flip_to_front('\ue62f'),
		gmd_get_app('\ue630'),
		gmd_grade('\ue631'),
		gmd_group_work('\ue632'),
		gmd_help('\ue633'),
		gmd_highlight_remove('\ue634'),
		gmd_history('\ue635'),
		gmd_home('\ue636'),
		gmd_https('\ue637'),
		gmd_info('\ue638'),
		gmd_info_outline('\ue639'),
		gmd_input('\ue63a'),
		gmd_invert_colors('\ue63b'),
		gmd_label('\ue63c'),
		gmd_label_outline('\ue63d'),
		gmd_language('\ue63e'),
		gmd_launch('\ue63f'),
		gmd_list('\ue640'),
		gmd_lock('\ue641'),
		gmd_lock_open('\ue642'),
		gmd_lock_outline('\ue643'),
		gmd_loyalty('\ue644'),
		gmd_markunread_mailbox('\ue645'),
		gmd_note_add('\ue646'),
		gmd_open_in_browser('\ue647'),
		gmd_open_in_new('\ue648'),
		gmd_open_with('\ue649'),
		gmd_pageview('\ue64a'),
		gmd_payment('\ue64b'),
		gmd_perm_camera_m('\ue64c'),
		gmd_perm_contact_cal('\ue64d'),
		gmd_perm_data_setting('\ue64e'),
		gmd_perm_device_info('\ue64f'),
		gmd_perm_identity('\ue650'),
		gmd_perm_media('\ue651'),
		gmd_perm_phone_msg('\ue652'),
		gmd_perm_scan_wifi('\ue653'),
		gmd_picture_in_picture('\ue654'),
		gmd_polymer('\ue655'),
		gmd_print('\ue656'),
		gmd_query_builder('\ue657'),
		gmd_question_answer('\ue658'),
		gmd_receipt('\ue659'),
		gmd_redeem('\ue65a'),
		gmd_reorder('\ue65b'),
		gmd_report_problem('\ue65c'),
		gmd_restore('\ue65d'),
		gmd_room('\ue65e'),
		gmd_schedule('\ue65f'),
		gmd_search('\ue660'),
		gmd_settings('\ue661'),
		gmd_settings_applications('\ue662'),
		gmd_settings_backup_restore('\ue663'),
		gmd_settings_bluetooth('\ue664'),
		gmd_settings_cell('\ue665'),
		gmd_settings_display('\ue666'),
		gmd_settings_ethernet('\ue667'),
		gmd_settings_input_antenna('\ue668'),
		gmd_settings_input_component('\ue669'),
		gmd_settings_input_composite('\ue66a'),
		gmd_settings_input_hdmi('\ue66b'),
		gmd_settings_input_svideo('\ue66c'),
		gmd_settings_overscan('\ue66d'),
		gmd_settings_phone('\ue66e'),
		gmd_settings_power('\ue66f'),
		gmd_settings_remote('\ue670'),
		gmd_settings_voice('\ue671'),
		gmd_shop('\ue672'),
		gmd_shop_two('\ue673'),
		gmd_shopping_basket('\ue674'),
		gmd_shopping_cart('\ue675'),
		gmd_speaker_notes('\ue676'),
		gmd_spellcheck('\ue677'),
		gmd_star_rate('\ue678'),
		gmd_stars('\ue679'),
		gmd_store('\ue67a'),
		gmd_subject('\ue67b'),
		gmd_supervisor_account('\ue67c'),
		gmd_swap_horiz('\ue67d'),
		gmd_swap_vert('\ue67e'),
		gmd_swap_vert_circle('\ue67f'),
		gmd_system_update_tv('\ue680'),
		gmd_tab('\ue681'),
		gmd_tab_unselected('\ue682'),
		gmd_theaters('\ue683'),
		gmd_thumb_down('\ue684'),
		gmd_thumb_up('\ue685'),
		gmd_thumbs_up_down('\ue686'),
		gmd_toc('\ue687'),
		gmd_today('\ue688'),
		gmd_track_changes('\ue689'),
		gmd_translate('\ue68a'),
		gmd_trending_down('\ue68b'),
		gmd_trending_neutral('\ue68c'),
		gmd_trending_up('\ue68d'),
		gmd_turned_in('\ue68e'),
		gmd_turned_in_not('\ue68f'),
		gmd_verified_user('\ue690'),
		gmd_view_agenda('\ue691'),
		gmd_view_array('\ue692'),
		gmd_view_carousel('\ue693'),
		gmd_view_column('\ue694'),
		gmd_view_day('\ue695'),
		gmd_view_headline('\ue696'),
		gmd_view_list('\ue697'),
		gmd_view_module('\ue698'),
		gmd_view_quilt('\ue699'),
		gmd_view_stream('\ue69a'),
		gmd_view_week('\ue69b'),
		gmd_visibility('\ue69c'),
		gmd_visibility_off('\ue69d'),
		gmd_wallet_giftcard('\ue69e'),
		gmd_wallet_membership('\ue69f'),
		gmd_wallet_travel('\ue6a0'),
		gmd_work('\ue6a1'),
		gmd_error('\ue6a2'),
		gmd_warning('\ue6a3'),
		gmd_album('\ue6a4'),
		gmd_av_timer('\ue6a5'),
		gmd_closed_caption('\ue6a6'),
		gmd_equalizer('\ue6a7'),
		gmd_explicit('\ue6a8'),
		gmd_fast_forward('\ue6a9'),
		gmd_fast_rewind('\ue6aa'),
		gmd_games('\ue6ab'),
		gmd_hearing('\ue6ac'),
		gmd_high_quality('\ue6ad'),
		gmd_loop('\ue6ae'),
		gmd_mic('\ue6af'),
		gmd_mnone('\ue6b0'),
		gmd_moff('\ue6b1'),
		gmd_movie('\ue6b2'),
		gmd_my_library_add('\ue6b3'),
		gmd_my_library_books('\ue6b4'),
		gmd_my_library_mus('\ue6b5'),
		gmd_new_releases('\ue6b6'),
		gmd_not_interested('\ue6b7'),
		gmd_pause('\ue6b8'),
		gmd_pause_circle_fill('\ue6b9'),
		gmd_pause_circle_outline('\ue6ba'),
		gmd_play_arrow('\ue6bb'),
		gmd_play_circle_fill('\ue6bc'),
		gmd_play_circle_outline('\ue6bd'),
		gmd_play_shopping_bag('\ue6be'),
		gmd_playlist_add('\ue6bf'),
		gmd_queue('\ue6c0'),
		gmd_queue_mus('\ue6c1'),
		gmd_radio('\ue6c2'),
		gmd_recent_actors('\ue6c3'),
		gmd_repeat('\ue6c4'),
		gmd_repeat_one('\ue6c5'),
		gmd_replay('\ue6c6'),
		gmd_shuffle('\ue6c7'),
		gmd_skip_next('\ue6c8'),
		gmd_skip_previous('\ue6c9'),
		gmd_snooze('\ue6ca'),
		gmd_stop('\ue6cb'),
		gmd_subtitles('\ue6cc'),
		gmd_surround_sound('\ue6cd'),
		gmd_video_collection('\ue6ce'),
		gmd_videocam('\ue6cf'),
		gmd_videocam_off('\ue6d0'),
		gmd_volume_down('\ue6d1'),
		gmd_volume_mute('\ue6d2'),
		gmd_volume_off('\ue6d3'),
		gmd_volume_up('\ue6d4'),
		gmd_web('\ue6d5'),
		gmd_business('\ue6d6'),
		gmd_call('\ue6d7'),
		gmd_call_end('\ue6d8'),
		gmd_call_made('\ue6d9'),
		gmd_call_merge('\ue6da'),
		gmd_call_missed('\ue6db'),
		gmd_call_received('\ue6dc'),
		gmd_call_split('\ue6dd'),
		gmd_chat('\ue6de'),
		gmd_clear_all('\ue6df'),
		gmd_comment('\ue6e0'),
		gmd_contacts('\ue6e1'),
		gmd_dialer_sip('\ue6e2'),
		gmd_dialpad('\ue6e3'),
		gmd_dnd_on('\ue6e4'),
		gmd_email('\ue6e5'),
		gmd_forum('\ue6e6'),
		gmd_import_export('\ue6e7'),
		gmd_invert_colors_off('\ue6e8'),
		gmd_invert_colors_on('\ue6e9'),
		gmd_live_help('\ue6ea'),
		gmd_location_off('\ue6eb'),
		gmd_location_on('\ue6ec'),
		gmd_message('\ue6ed'),
		gmd_messenger('\ue6ee'),
		gmd_no_sim('\ue6ef'),
		gmd_phone('\ue6f0'),
		gmd_portable_wifi_off('\ue6f1'),
		gmd_quick_contacts_dialer('\ue6f2'),
		gmd_quick_contacts_mail('\ue6f3'),
		gmd_ring_volume('\ue6f4'),
		gmd_stay_current_landscape('\ue6f5'),
		gmd_stay_current_portrait('\ue6f6'),
		gmd_stay_primary_landscape('\ue6f7'),
		gmd_stay_primary_portrait('\ue6f8'),
		gmd_swap_calls('\ue6f9'),
		gmd_textsms('\ue6fa'),
		gmd_voicemail('\ue6fb'),
		gmd_vpn_key('\ue6fc'),
		gmd_add('\ue6fd'),
		gmd_add_box('\ue6fe'),
		gmd_add_circle('\ue6ff'),
		gmd_add_circle_outline('\ue700'),
		gmd_archive('\ue701'),
		gmd_backspace('\ue702'),
		gmd_block('\ue703'),
		gmd_clear('\ue704'),
		gmd_content_copy('\ue705'),
		gmd_content_cut('\ue706'),
		gmd_content_paste('\ue707'),
		gmd_create('\ue708'),
		gmd_drafts('\ue709'),
		gmd_filter_list('\ue70a'),
		gmd_flag('\ue70b'),
		gmd_forward('\ue70c'),
		gmd_gesture('\ue70d'),
		gmd_inbox('\ue70e'),
		gmd_link('\ue70f'),
		gmd_mail('\ue710'),
		gmd_markunread('\ue711'),
		gmd_redo('\ue712'),
		gmd_remove('\ue713'),
		gmd_remove_circle('\ue714'),
		gmd_remove_circle_outline('\ue715'),
		gmd_reply('\ue716'),
		gmd_reply_all('\ue717'),
		gmd_report('\ue718'),
		gmd_save('\ue719'),
		gmd_select_all('\ue71a'),
		gmd_send('\ue71b'),
		gmd_sort('\ue71c'),
		gmd_text_format('\ue71d'),
		gmd_undo('\ue71e'),
		gmd_access_alarm('\ue71f'),
		gmd_access_alarms('\ue720'),
		gmd_access_time('\ue721'),
		gmd_add_alarm('\ue722'),
		gmd_airplanemode_off('\ue723'),
		gmd_airplanemode_on('\ue724'),
		gmd_battery_20('\ue725'),
		gmd_battery_30('\ue726'),
		gmd_battery_50('\ue727'),
		gmd_battery_60('\ue728'),
		gmd_battery_80('\ue729'),
		gmd_battery_90('\ue72a'),
		gmd_battery_alert('\ue72b'),
		gmd_battery_charging_20('\ue72c'),
		gmd_battery_charging_30('\ue72d'),
		gmd_battery_charging_50('\ue72e'),
		gmd_battery_charging_60('\ue72f'),
		gmd_battery_charging_80('\ue730'),
		gmd_battery_charging_90('\ue731'),
		gmd_battery_charging_full('\ue732'),
		gmd_battery_full('\ue733'),
		gmd_battery_std('\ue734'),
		gmd_battery_unknown('\ue735'),
		gmd_bluetooth('\ue736'),
		gmd_bluetooth_connected('\ue737'),
		gmd_bluetooth_disabled('\ue738'),
		gmd_bluetooth_searching('\ue739'),
		gmd_brightness_auto('\ue73a'),
		gmd_brightness_high('\ue73b'),
		gmd_brightness_low('\ue73c'),
		gmd_brightness_medium('\ue73d'),
		gmd_data_usage('\ue73e'),
		gmd_developer_mode('\ue73f'),
		gmd_devices('\ue740'),
		gmd_dvr('\ue741'),
		gmd_gps_fixed('\ue742'),
		gmd_gps_not_fixed('\ue743'),
		gmd_gps_off('\ue744'),
		gmd_location_disabled('\ue745'),
		gmd_location_searching('\ue746'),
		gmd_multitrack_audio('\ue747'),
		gmd_network_cell('\ue748'),
		gmd_network_wifi('\ue749'),
		gmd_nfc('\ue74a'),
		gmd_now_wallpaper('\ue74b'),
		gmd_now_widgets('\ue74c'),
		gmd_screen_lock_landscape('\ue74d'),
		gmd_screen_lock_portrait('\ue74e'),
		gmd_screen_lock_rotation('\ue74f'),
		gmd_screen_rotation('\ue750'),
		gmd_sd_storage('\ue751'),
		gmd_settings_system_daydream('\ue752'),
		gmd_signal_cellular_0_bar('\ue753'),
		gmd_signal_cellular_1_bar('\ue754'),
		gmd_signal_cellular_2_bar('\ue755'),
		gmd_signal_cellular_3_bar('\ue756'),
		gmd_signal_cellular_4_bar('\ue757'),
		gmd_signal_cellular_connected_no_internet_0_bar('\ue758'),
		gmd_signal_cellular_connected_no_internet_1_bar('\ue759'),
		gmd_signal_cellular_connected_no_internet_2_bar('\ue75a'),
		gmd_signal_cellular_connected_no_internet_3_bar('\ue75b'),
		gmd_signal_cellular_connected_no_internet_4_bar('\ue75c'),
		gmd_signal_cellular_no_sim('\ue75d'),
		gmd_signal_cellular_null('\ue75e'),
		gmd_signal_cellular_off('\ue75f'),
		gmd_signal_wifi_0_bar('\ue760'),
		gmd_signal_wifi_1_bar('\ue761'),
		gmd_signal_wifi_2_bar('\ue762'),
		gmd_signal_wifi_3_bar('\ue763'),
		gmd_signal_wifi_4_bar('\ue764'),
		gmd_signal_wifi_off('\ue765'),
		gmd_signal_wifi_statusbar_1_bar('\ue766'),
		gmd_signal_wifi_statusbar_2_bar('\ue767'),
		gmd_signal_wifi_statusbar_3_bar('\ue768'),
		gmd_signal_wifi_statusbar_4_bar('\ue769'),
		gmd_signal_wifi_statusbar_connected_no_internet_1('\ue76a'),
		gmd_signal_wifi_statusbar_connected_no_internet_2('\ue76b'),
		gmd_signal_wifi_statusbar_connected_no_internet_3('\ue76c'),
		gmd_signal_wifi_statusbar_connected_no_internet_4('\ue76d'),
		gmd_signal_wifi_statusbar_connected_no_internet('\ue76e'),
		gmd_signal_wifi_statusbar_not_connected('\ue76f'),
		gmd_signal_wifi_statusbar_null('\ue770'),
		gmd_storage('\ue771'),
		gmd_usb('\ue772'),
		gmd_wifi_lock('\ue773'),
		gmd_wifi_tethering('\ue774'),
		gmd_attach_file('\ue775'),
		gmd_attach_money('\ue776'),
		gmd_border_all('\ue777'),
		gmd_border_bottom('\ue778'),
		gmd_border_clear('\ue779'),
		gmd_border_color('\ue77a'),
		gmd_border_horizontal('\ue77b'),
		gmd_border_inner('\ue77c'),
		gmd_border_left('\ue77d'),
		gmd_border_outer('\ue77e'),
		gmd_border_right('\ue77f'),
		gmd_border_style('\ue780'),
		gmd_border_top('\ue781'),
		gmd_border_vertical('\ue782'),
		gmd_format_align_center('\ue783'),
		gmd_format_align_justify('\ue784'),
		gmd_format_align_left('\ue785'),
		gmd_format_align_right('\ue786'),
		gmd_format_bold('\ue787'),
		gmd_format_clear('\ue788'),
		gmd_format_color_fill('\ue789'),
		gmd_format_color_reset('\ue78a'),
		gmd_format_color_text('\ue78b'),
		gmd_format_indent_decrease('\ue78c'),
		gmd_format_indent_increase('\ue78d'),
		gmd_format_ital('\ue78e'),
		gmd_format_line_spacing('\ue78f'),
		gmd_format_list_bulleted('\ue790'),
		gmd_format_list_numbered('\ue791'),
		gmd_format_paint('\ue792'),
		gmd_format_quote('\ue793'),
		gmd_format_size('\ue794'),
		gmd_format_strikethrough('\ue795'),
		gmd_format_textdirection_l_to_r('\ue796'),
		gmd_format_textdirection_r_to_l('\ue797'),
		gmd_format_underline('\ue798'),
		gmd_functions('\ue799'),
		gmd_insert_chart('\ue79a'),
		gmd_insert_comment('\ue79b'),
		gmd_insert_drive_file('\ue79c'),
		gmd_insert_emoticon('\ue79d'),
		gmd_insert_invitation('\ue79e'),
		gmd_insert_link('\ue79f'),
		gmd_insert_photo('\ue7a0'),
		gmd_merge_type('\ue7a1'),
		gmd_mode_comment('\ue7a2'),
		gmd_mode_edit('\ue7a3'),
		gmd_publish('\ue7a4'),
		gmd_vertical_align_bottom('\ue7a5'),
		gmd_vertical_align_center('\ue7a6'),
		gmd_vertical_align_top('\ue7a7'),
		gmd_wrap_text('\ue7a8'),
		gmd_attachment('\ue7a9'),
		gmd_cloud('\ue7aa'),
		gmd_cloud_circle('\ue7ab'),
		gmd_cloud_done('\ue7ac'),
		gmd_cloud_download('\ue7ad'),
		gmd_cloud_off('\ue7ae'),
		gmd_cloud_queue('\ue7af'),
		gmd_cloud_upload('\ue7b0'),
		gmd_file_download('\ue7b1'),
		gmd_file_upload('\ue7b2'),
		gmd_folder('\ue7b3'),
		gmd_folder_open('\ue7b4'),
		gmd_folder_shared('\ue7b5'),
		gmd_cast('\ue7b6'),
		gmd_cast_connected('\ue7b7'),
		gmd_computer('\ue7b8'),
		gmd_desktop_mac('\ue7b9'),
		gmd_desktop_windows('\ue7ba'),
		gmd_dock('\ue7bb'),
		gmd_gamepad('\ue7bc'),
		gmd_headset('\ue7bd'),
		gmd_headset_m('\ue7be'),
		gmd_keyboard('\ue7bf'),
		gmd_keyboard_alt('\ue7c0'),
		gmd_keyboard_arrow_down('\ue7c1'),
		gmd_keyboard_arrow_left('\ue7c2'),
		gmd_keyboard_arrow_right('\ue7c3'),
		gmd_keyboard_arrow_up('\ue7c4'),
		gmd_keyboard_backspace('\ue7c5'),
		gmd_keyboard_capslock('\ue7c6'),
		gmd_keyboard_control('\ue7c7'),
		gmd_keyboard_hide('\ue7c8'),
		gmd_keyboard_return('\ue7c9'),
		gmd_keyboard_tab('\ue7ca'),
		gmd_keyboard_voice('\ue7cb'),
		gmd_laptop('\ue7cc'),
		gmd_laptop_chromebook('\ue7cd'),
		gmd_laptop_mac('\ue7ce'),
		gmd_laptop_windows('\ue7cf'),
		gmd_memory('\ue7d0'),
		gmd_mouse('\ue7d1'),
		gmd_phone_android('\ue7d2'),
		gmd_phone_iphone('\ue7d3'),
		gmd_phonelink('\ue7d4'),
		gmd_phonelink_off('\ue7d5'),
		gmd_security('\ue7d6'),
		gmd_sim_card('\ue7d7'),
		gmd_smartphone('\ue7d8'),
		gmd_speaker('\ue7d9'),
		gmd_tablet('\ue7da'),
		gmd_tablet_android('\ue7db'),
		gmd_tablet_mac('\ue7dc'),
		gmd_tv('\ue7dd'),
		gmd_watch('\ue7de'),
		gmd_add_to_photos('\ue7df'),
		gmd_adjust('\ue7e0'),
		gmd_assistant_photo('\ue7e1'),
		gmd_audiotrack('\ue7e2'),
		gmd_blur_circular('\ue7e3'),
		gmd_blur_linear('\ue7e4'),
		gmd_blur_off('\ue7e5'),
		gmd_blur_on('\ue7e6'),
		gmd_brightness_1('\ue7e7'),
		gmd_brightness_2('\ue7e8'),
		gmd_brightness_3('\ue7e9'),
		gmd_brightness_4('\ue7ea'),
		gmd_brightness_5('\ue7eb'),
		gmd_brightness_6('\ue7ec'),
		gmd_brightness_7('\ue7ed'),
		gmd_brush('\ue7ee'),
		gmd_camera('\ue7ef'),
		gmd_camera_alt('\ue7f0'),
		gmd_camera_front('\ue7f1'),
		gmd_camera_rear('\ue7f2'),
		gmd_camera_roll('\ue7f3'),
		gmd_center_focus_strong('\ue7f4'),
		gmd_center_focus_weak('\ue7f5'),
		gmd_collections('\ue7f6'),
		gmd_color_lens('\ue7f7'),
		gmd_colorize('\ue7f8'),
		gmd_compare('\ue7f9'),
		gmd_control_point('\ue7fa'),
		gmd_control_point_duplicate('\ue7fb'),
		gmd_crop_3_2('\ue7fc'),
		gmd_crop_5_4('\ue7fd'),
		gmd_crop_7_5('\ue7fe'),
		gmd_crop_16_9('\ue7ff'),
		gmd_crop('\ue800'),
		gmd_crop_din('\ue801'),
		gmd_crop_free('\ue802'),
		gmd_crop_landscape('\ue803'),
		gmd_crop_original('\ue804'),
		gmd_crop_portrait('\ue805'),
		gmd_crop_square('\ue806'),
		gmd_dehaze('\ue807'),
		gmd_details('\ue808'),
		gmd_edit('\ue809'),
		gmd_exposure('\ue80a'),
		gmd_exposure_minus_1('\ue80b'),
		gmd_exposure_minus_2('\ue80c'),
		gmd_exposure_plus_1('\ue80d'),
		gmd_exposure_plus_2('\ue80e'),
		gmd_exposure_zero('\ue80f'),
		gmd_filter_1('\ue810'),
		gmd_filter_2('\ue811'),
		gmd_filter_3('\ue812'),
		gmd_filter_4('\ue813'),
		gmd_filter_5('\ue814'),
		gmd_filter_6('\ue815'),
		gmd_filter_7('\ue816'),
		gmd_filter_8('\ue817'),
		gmd_filter_9('\ue818'),
		gmd_filter_9_plus('\ue819'),
		gmd_filter('\ue81a'),
		gmd_filter_b_and_w('\ue81b'),
		gmd_filter_center_focus('\ue81c'),
		gmd_filter_drama('\ue81d'),
		gmd_filter_frames('\ue81e'),
		gmd_filter_hdr('\ue81f'),
		gmd_filter_none('\ue820'),
		gmd_filter_tilt_shift('\ue821'),
		gmd_filter_vintage('\ue822'),
		gmd_flare('\ue823'),
		gmd_flash_auto('\ue824'),
		gmd_flash_off('\ue825'),
		gmd_flash_on('\ue826'),
		gmd_flip('\ue827'),
		gmd_gradient('\ue828'),
		gmd_grain('\ue829'),
		gmd_grid_off('\ue82a'),
		gmd_grid_on('\ue82b'),
		gmd_hdr_off('\ue82c'),
		gmd_hdr_on('\ue82d'),
		gmd_hdr_strong('\ue82e'),
		gmd_hdr_weak('\ue82f'),
		gmd_healing('\ue830'),
		gmd_image('\ue831'),
		gmd_image_aspect_ratio('\ue832'),
		gmd_iso('\ue833'),
		gmd_landscape('\ue834'),
		gmd_leak_add('\ue835'),
		gmd_leak_remove('\ue836'),
		gmd_lens('\ue837'),
		gmd_looks_3('\ue838'),
		gmd_looks_4('\ue839'),
		gmd_looks_5('\ue83a'),
		gmd_looks_6('\ue83b'),
		gmd_looks('\ue83c'),
		gmd_looks_one('\ue83d'),
		gmd_looks_two('\ue83e'),
		gmd_loupe('\ue83f'),
		gmd_movie_creation('\ue840'),
		gmd_nature('\ue841'),
		gmd_nature_people('\ue842'),
		gmd_navigate_before('\ue843'),
		gmd_navigate_next('\ue844'),
		gmd_palette('\ue845'),
		gmd_panorama('\ue846'),
		gmd_panorama_fisheye('\ue847'),
		gmd_panorama_horizontal('\ue848'),
		gmd_panorama_vertical('\ue849'),
		gmd_panorama_wide_angle('\ue84a'),
		gmd_photo('\ue84b'),
		gmd_photo_album('\ue84c'),
		gmd_photo_camera('\ue84d'),
		gmd_photo_library('\ue84e'),
		gmd_portrait('\ue84f'),
		gmd_remove_red_eye('\ue850'),
		gmd_rotate_left('\ue851'),
		gmd_rotate_right('\ue852'),
		gmd_slideshow('\ue853'),
		gmd_straighten('\ue854'),
		gmd_style('\ue855'),
		gmd_switch_camera('\ue856'),
		gmd_switch_video('\ue857'),
		gmd_tag_faces('\ue858'),
		gmd_texture('\ue859'),
		gmd_timelapse('\ue85a'),
		gmd_timer_3('\ue85b'),
		gmd_timer_10('\ue85c'),
		gmd_timer('\ue85d'),
		gmd_timer_auto('\ue85e'),
		gmd_timer_off('\ue85f'),
		gmd_tonality('\ue860'),
		gmd_transform('\ue861'),
		gmd_tune('\ue862'),
		gmd_wb_auto('\ue863'),
		gmd_wb_cloudy('\ue864'),
		gmd_wb_incandescent('\ue865'),
		gmd_wb_irradescent('\ue866'),
		gmd_wb_sunny('\ue867'),
		gmd_beenhere('\ue868'),
		gmd_directions('\ue869'),
		gmd_directions_bike('\ue86a'),
		gmd_directions_bus('\ue86b'),
		gmd_directions_car('\ue86c'),
		gmd_directions_ferry('\ue86d'),
		gmd_directions_subway('\ue86e'),
		gmd_directions_train('\ue86f'),
		gmd_directions_transit('\ue870'),
		gmd_directions_walk('\ue871'),
		gmd_flight('\ue872'),
		gmd_hotel('\ue873'),
		gmd_layers('\ue874'),
		gmd_layers_clear('\ue875'),
		gmd_local_airport('\ue876'),
		gmd_local_atm('\ue877'),
		gmd_local_attraction('\ue878'),
		gmd_local_bar('\ue879'),
		gmd_local_cafe('\ue87a'),
		gmd_local_car_wash('\ue87b'),
		gmd_local_convenience_store('\ue87c'),
		gmd_local_drink('\ue87d'),
		gmd_local_florist('\ue87e'),
		gmd_local_gas_station('\ue87f'),
		gmd_local_grocery_store('\ue880'),
		gmd_local_hospital('\ue881'),
		gmd_local_hotel('\ue882'),
		gmd_local_laundry_service('\ue883'),
		gmd_local_library('\ue884'),
		gmd_local_mall('\ue885'),
		gmd_local_movies('\ue886'),
		gmd_local_offer('\ue887'),
		gmd_local_parking('\ue888'),
		gmd_local_pharmacy('\ue889'),
		gmd_local_phone('\ue88a'),
		gmd_local_pizza('\ue88b'),
		gmd_local_play('\ue88c'),
		gmd_local_post_office('\ue88d'),
		gmd_local_print_shop('\ue88e'),
		gmd_local_restaurant('\ue88f'),
		gmd_local_see('\ue890'),
		gmd_local_shipping('\ue891'),
		gmd_local_taxi('\ue892'),
		gmd_location_history('\ue893'),
		gmd_map('\ue894'),
		gmd_my_location('\ue895'),
		gmd_navigation('\ue896'),
		gmd_pin_drop('\ue897'),
		gmd_place('\ue898'),
		gmd_rate_review('\ue899'),
		gmd_restaurant_menu('\ue89a'),
		gmd_satellite('\ue89b'),
		gmd_store_mall_directory('\ue89c'),
		gmd_terrain('\ue89d'),
		gmd_traff('\ue89e'),
		gmd_apps('\ue89f'),
		gmd_arrow_back('\ue8a0'),
		gmd_arrow_drop_down('\ue8a1'),
		gmd_arrow_drop_down_circle('\ue8a2'),
		gmd_arrow_drop_up('\ue8a3'),
		gmd_arrow_forward('\ue8a4'),
		gmd_cancel('\ue8a5'),
		gmd_check('\ue8a6'),
		gmd_chevron_left('\ue8a7'),
		gmd_chevron_right('\ue8a8'),
		gmd_close('\ue8a9'),
		gmd_expand_less('\ue8aa'),
		gmd_expand_more('\ue8ab'),
		gmd_fullscreen('\ue8ac'),
		gmd_fullscreen_exit('\ue8ad'),
		gmd_menu('\ue8ae'),
		gmd_more_horiz('\ue8af'),
		gmd_more_vert('\ue8b0'),
		gmd_refresh('\ue8b1'),
		gmd_unfold_less('\ue8b2'),
		gmd_unfold_more('\ue8b3'),
		gmd_adb('\ue8b4'),
		gmd_bluetooth_audio('\ue8b5'),
		gmd_disc_full('\ue8b6'),
		gmd_dnd_forwardslash('\ue8b7'),
		gmd_do_not_disturb('\ue8b8'),
		gmd_drive_eta('\ue8b9'),
		gmd_event_available('\ue8ba'),
		gmd_event_busy('\ue8bb'),
		gmd_event_note('\ue8bc'),
		gmd_folder_special('\ue8bd'),
		gmd_mms('\ue8be'),
		gmd_more('\ue8bf'),
		gmd_network_locked('\ue8c0'),
		gmd_phone_bluetooth_speaker('\ue8c1'),
		gmd_phone_forwarded('\ue8c2'),
		gmd_phone_in_talk('\ue8c3'),
		gmd_phone_locked('\ue8c4'),
		gmd_phone_missed('\ue8c5'),
		gmd_phone_paused('\ue8c6'),
		gmd_play_download('\ue8c7'),
		gmd_play_install('\ue8c8'),
		gmd_sd_card('\ue8c9'),
		gmd_sim_card_alert('\ue8ca'),
		gmd_sms('\ue8cb'),
		gmd_sms_failed('\ue8cc'),
		gmd_sync('\ue8cd'),
		gmd_sync_disabled('\ue8ce'),
		gmd_sync_problem('\ue8cf'),
		gmd_system_update('\ue8d0'),
		gmd_tap_and_play('\ue8d1'),
		gmd_time_to_leave('\ue8d2'),
		gmd_vibration('\ue8d3'),
		gmd_voice_chat('\ue8d4'),
		gmd_vpn_lock('\ue8d5'),
		gmd_cake('\ue8d6'),
		gmd_domain('\ue8d7'),
		gmd_group('\ue8d8'),
		gmd_group_add('\ue8d9'),
		gmd_location_city('\ue8da'),
		gmd_mood('\ue8db'),
		gmd_notifications('\ue8dc'),
		gmd_notifications_none('\ue8dd'),
		gmd_notifications_off('\ue8de'),
		gmd_notifications_on('\ue8df'),
		gmd_notifications_paused('\ue8e0'),
		gmd_pages('\ue8e1'),
		gmd_party_mode('\ue8e2'),
		gmd_people('\ue8e3'),
		gmd_people_outline('\ue8e4'),
		gmd_person('\ue8e5'),
		gmd_person_add('\ue8e6'),
		gmd_person_outline('\ue8e7'),
		gmd_plus_one('\ue8e8'),
		gmd_poll('\ue8e9'),
		gmd_publ('\ue8ea'),
		gmd_school('\ue8eb'),
		gmd_share('\ue8ec'),
		gmd_whatshot('\ue8ed'),
		gmd_check_box('\ue8ee'),
		gmd_check_box_outline_blank('\ue8ef'),
		gmd_radio_button_off('\ue8f0'),
		gmd_radio_button_on('\ue8f1'),
		gmd_star('\ue8f2'),
		gmd_star_half('\ue8f3'),
		gmd_star_outline('\ue8f4');

		char character;

		IconValue(char character) {
			this.character = character;
		}

		public String formattedName() {
			return "{" + name() + "}";
		}

		public char character() {
			return character;
		}
	}
}
